---
title: "PR1. Viusalització de dades"
author: "Catalina Maria Mercer Campins"
date: "2025-11-20"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r load_libraries, include=FALSE}
library(readxl) 
library(readr)
library(dplyr)
library(ggplot2)
library(car)
library(knitr)
library(tidyverse)
library(tidyr)
library(stringr)
library(DT)
library(writexl)
```

```{r}
# Carregam les dades
music = read.csv("../data/Music_Info.csv", check.names = FALSE)
count = read.csv("../data/User_Listening_History.csv", check.names = FALSE)
```


```{r}
names(music)
```


```{r}
names(count)
```

```{r}
contador = group_by(count, track_id)
contador = summarise(contador, total_plays = sum(playcount, na.rm = TRUE))
full_data = left_join(contador, music, by = "track_id")
full_data
```


Netejam el dataset

```{r}
# per si hi ha duplicats de track_id
music_clean = distinct(full_data, track_id, .keep_all = TRUE)

# eliminam variables
#music_clean = select(music_clean, -spotify_preview_url, -spotify_id)
music_clean = select(music_clean, -spotify_id)
                     

# assegurar que les variables numèriques són numèriques
music_clean = mutate(music_clean,
    total_plays     = as.numeric(total_plays),
    year            = as.integer(year),
    duration_ms     = as.numeric(duration_ms),
    danceability    = as.numeric(danceability),
    energy          = as.numeric(energy),
    key             = as.integer(key),
    loudness        = as.numeric(loudness),
    mode            = as.integer(mode),
    speechiness     = as.numeric(speechiness),
    acousticness    = as.numeric(acousticness),
    instrumentalness= as.numeric(instrumentalness),
    liveness        = as.numeric(liveness),
    valence         = as.numeric(valence),
    tempo           = as.numeric(tempo),
    time_signature  = as.integer(time_signature)
  )
```


```{r}
music_clean = mutate(music_clean,
    # any impossible → NA
    year = ifelse(year < 1900 | year > 2025, NA_integer_, year),
    # afegir durada en minuts (útil per a visualitzacions)
    duration_min = duration_ms / 60000)
```


```{r}
# funció auxiliar per marcar com NA valors fora de [0,1]
cap_01 = function(x) ifelse(x < 0 | x > 1, NA_real_, x)

music_clean = mutate(music_clean,
    danceability     = cap_01(danceability),
    energy           = cap_01(energy),
    speechiness      = cap_01(speechiness),
    acousticness     = cap_01(acousticness),
    instrumentalness = cap_01(instrumentalness),
    liveness         = cap_01(liveness),
    valence          = cap_01(valence),
    # loudness: normalment entre -60 i 0 dB
    loudness = ifelse(loudness < -60 | loudness > 5, NA_real_, loudness),
    # tempo raonable
    tempo = ifelse(tempo <= 0 | tempo > 300, NA_real_, tempo)
  )

```

```{r}
music_clean = mutate(music_clean,
    name   = str_squish(name),
    artist = str_squish(artist),
    # normalitzar gènere
    genre  = genre |> 
      tolower() |>
      str_squish(),
    genre  = ifelse(genre == "" , NA_character_, genre),
    # netejar tags (text lliure)
    tags   = tags |>
      tolower() |>
      str_squish(),
    tags   = ifelse(tags == "" , NA_character_, tags)
  )

```

```{r}
music_clean = filter(music_clean, total_plays > 0)
```


Intentem omplir els NAs de Genere

```{r}
# Genere te molts NAs
sum(is.na(music_clean$genre))
```


```{r}
detect_genre_from_tags <- function(tags) {
  case_when(
    str_detect(tags, "death_metal|black_metal|doom_metal|thrash_metal|power_metal|melodic_death_metal|metalcore|hardcore|grindcore|progressive_metal|metal") ~ "metal",
    str_detect(tags, "\\brock\\b|alternative_rock|hard_rock|grunge|britpop|indie_rock|post_rock|punk_rock|punk|classic_rock|psychedelic_rock|indie|progressive_rock") ~ "rock",
    str_detect(tags, "\\bpop\\b|dance_pop|electropop|indie_pop") ~ "pop",
    str_detect(tags, "hip_hop|\\brap\\b|trap|trip_hop") ~ "hip hop",
    str_detect(tags, "electronic|electro|house|techno|edm|trance|drum_and_bass|downtempo| lounge|industrial|lounge|ambient") ~ "electronic",
    str_detect(tags, "jazz|blues|soul|funk|rnb") ~ "jazz & soul",
    str_detect(tags, "folk|singer_songwriter|acoustic") ~ "folk",
    str_detect(tags, "classical|piano|opera|orchestral") ~ "classical",
    str_detect(tags, "\\bska\\b|reggae") ~ "reggae",
    str_detect(tags, "country") ~ "country",
    str_detect(tags, "new_age") ~ "new age",
    TRUE ~ NA_character_
  )
}


music_clean = mutate(music_clean,
    genre_filled = if_else(is.na(genre),
      detect_genre_from_tags(tags),
      genre))

```

```{r}
#music_clean = filter(music_clean, is.na(genre_filled)) 
#music_clean = count(music_clean, tags, sort = TRUE)
```

```{r}
# Nombre de NAs despres de rellenar amb tags
sum(is.na(music_clean$genre_filled))
```


```{r}
genre_counts = filter(music_clean, !is.na(genre_filled))
genre_counts = count(genre_counts, genre_filled, sort = TRUE)
genre_counts
```


Creació de noves variables:

```{r}
# normalització de popularitat
music_clean = mutate(music_clean, popularity_norm = total_plays / max(total_plays, na.rm = TRUE))
# creació de la variable mood
music_clean = mutate(music_clean, mood = (energy + valence) / 2)

# Agrupació de generes
music_clean = mutate(music_clean, genre_grouped = case_when(
    genre_filled %in% c("metal") ~ "Metal",
    genre_filled %in% c("rock", "punk") ~ "Rock",
    genre_filled %in% c("pop") ~ "Pop",
    genre_filled %in% c("hip hop", "rap") ~ "Hip hop",
    genre_filled %in% c("electronic") ~ "Electronic",
    genre_filled %in% c("folk") ~ "Folk",
    genre_filled %in% c("jazz", "rnb", "blues") ~ "Jazz & Soul",
    genre_filled %in% c("classical") ~ "Classical",
    genre_filled %in% c("reggae") ~ "Reggae",
    genre_filled %in% c("world") ~ "World",
    genre_filled %in% c("country") ~ "country",
    genre_filled %in% c("latin") ~ "Latin",
    TRUE ~ "other"
  ))

# Creació variable tipus de tempo (qualitativa)
music_clean =
  mutate(music_clean, tempo_class = case_when(
    tempo < 80 ~ "Slow",
    tempo < 120 ~ "Medium",
    TRUE ~ "Fast"
  ))

```



```{r}
# En CSV
write_csv(music_clean, "../data/data_clean.csv")
```

```{r}
datatable(music_clean)
```



```{r}
names(music_clean)
nrow(music_clean)
summary(music_clean$year)
```


Ens quedam entre els anys 1990 i 2020


```{r}
music_clean = filter(music_clean, !is.na(year),
                      year >= 1990, year <= 2020)
nrow(music_clean)
```

```{r}
music_scatter = select(music_clean, track_id, name, artist, year, genre_grouped, energy,
                      valence, mood, total_plays, popularity_norm, tempo_class) 
music_scatter = filter(music_scatter, !is.na(energy), !is.na(valence))

write_csv(music_scatter, "../outputs/music_scatter.csv")
```












```{r}
music_year = group_by(music_clean, year, genre_grouped) 
music_year = summarise(music_year, n_tracks = n(),
                      total_plays = sum(total_plays, na.rm = TRUE), .groups = "drop")
music_year_wide = group_by(music_year, year, genre_grouped)
music_year_wide = summarise(music_year_wide, n_tracks = sum(n_tracks, na.rm = TRUE),
                              total_plays = sum(total_plays, na.rm = TRUE), .groups = "drop")
music_year_wide = select(music_year_wide, year, genre_grouped, n_tracks)
music_year_wide = pivot_wider(music_year_wide, names_from = genre_grouped, 
                              values_from = n_tracks, values_fill = 0)


write_csv(music_year_wide, "../outputs/music_year.csv")

```



```{r}
music_race = group_by(music_clean, year, genre_grouped) 
music_race = summarise(music_race, total_plays = sum(total_plays, na.rm = TRUE),
                       .groups = "drop")

music_race_wide = pivot_wider(music_race, names_from = year, values_from = total_plays,
                              values_fill = 0 )

write_csv(music_race_wide, "../outputs/music_race.csv")

```

```{r}
total_genre = group_by(music_clean, genre_grouped) 
total_genre = summarise(total_genre, total_plays = sum(total_plays, na.rm = TRUE),
                       .groups = "drop")
total_genre = arrange(total_genre, desc(total_plays))
total_genre
```


```{r}

top10 = arrange(music_clean, desc(popularity_norm))
top10 = slice(top10, 1:10) 
top10 = select(top10, name, artist, energy, danceability, valence,
               acousticness, instrumentalness, genre_grouped, spotify_preview_url)
top10 = mutate(top10, track_label = paste(name, "-", artist))

write_csv(top10, "../outputs/top10_tracks_radar.csv")

```





```{r}
# Llindar d'alta popularitat (percentil 75)
llindar = quantile(music_clean$total_plays, 0.75, na.rm = TRUE)

high_pop = filter(music_clean, total_plays >= llindar)

high_pop_by_genre = group_by(high_pop, genre_grouped) 
high_pop_by_genre = summarise(high_pop_by_genre, n_high_pop_tracks = n(),
                            .groups = "drop")

write_csv(high_pop_by_genre, "../outputs/high_popularity_by_genre.csv")

```



```{r}
top_popularity = quantile(music_clean$popularity_norm, 0.9, na.rm = TRUE)
percent = mutate(music_clean, is_top = popularity_norm >= top_popularity)

percent = filter(percent, !is.na(genre_grouped)) 
percent = group_by(percent, genre_grouped)
percent = summarise(percent,
                              total_songs = n(), top_songs = sum(is_top, na.rm = TRUE),
                              perc_top = top_songs / total_songs * 100) 
percent = arrange(percent, desc(perc_top))
write_csv(percent, "../outputs/high_popularity_by_genre2.csv")
```
